name: Unit test and lint 
on: 
  push:
    branches: [ master ]
  pull_request:
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run test
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run lint
  build-and-deploy-project:
      needs: [run-lint, run-test]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - run: npm install
        - run: npm run build
        - name: Deploy to S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
            AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_AWS }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY_AWS }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            SOURCE_DIR: "build"
  